using System.Text.Json.Serialization;

namespace DrinksInfo.Model
{
    internal record class DrinkInfo(
        [property: JsonPropertyName("idDrink")] string ID,
        [property: JsonPropertyName("strDrink")] string Name,
        [property: JsonPropertyName("strDrinkAlternate")] string DrinkAlternate,
        [property: JsonPropertyName("strTags")] string Tags,
        [property: JsonPropertyName("strVideo")] string Video,
        [property: JsonPropertyName("strCategory")] string Category,
        [property: JsonPropertyName("strIBA")] string IBA,
        [property: JsonPropertyName("strAlcoholic")] string Alcoholic,
        [property: JsonPropertyName("strGlass")] string Glass,
        [property: JsonPropertyName("strInstructions")] string Insructions,
        [property: JsonPropertyName("strIngredient1")] string Ingredient1,
        [property: JsonPropertyName("strIngredient2")] string Ingredient2,
        [property: JsonPropertyName("strIngredient3")] string Ingredient3,
        [property: JsonPropertyName("strIngredient4")] string Ingredient4,
        [property: JsonPropertyName("strIngredient5")] string Ingredient5,
        [property: JsonPropertyName("strIngredient6")] string Ingredient6,
        [property: JsonPropertyName("strIngredient7")] string Ingredient7,
        [property: JsonPropertyName("strIngredient8")] string Ingredient8,
        [property: JsonPropertyName("strIngredient9")] string Ingredient9,
        [property: JsonPropertyName("strIngredient10")] string Ingredient10,
        [property: JsonPropertyName("strIngredient11")] string Ingredient11,
        [property: JsonPropertyName("strIngredient12")] string Ingredient12,
        [property: JsonPropertyName("strIngredient13")] string Ingredient13,
        [property: JsonPropertyName("strIngredient14")] string Ingredient14,
        [property: JsonPropertyName("strIngredient15")] string Ingredient15,
        [property: JsonPropertyName("strMeasure1")] string Measure1,
        [property: JsonPropertyName("strMeasure2")] string Measure2,
        [property: JsonPropertyName("strMeasure3")] string Measure3,
        [property: JsonPropertyName("strMeasure4")] string Measure4,
        [property: JsonPropertyName("strMeasure5")] string Measure5,
        [property: JsonPropertyName("strMeasure6")] string Measure6,
        [property: JsonPropertyName("strMeasure7")] string Measure7,
        [property: JsonPropertyName("strMeasure8")] string Measure8,
        [property: JsonPropertyName("strMeasure9")] string Measure9,
        [property: JsonPropertyName("strMeasure10")] string Measure10,
        [property: JsonPropertyName("strMeasure11")] string Measure11,
        [property: JsonPropertyName("strMeasure12")] string Measure12,
        [property: JsonPropertyName("strMeasure13")] string Measure13,
        [property: JsonPropertyName("strMeasure14")] string Measure14,
        [property: JsonPropertyName("strMeasure15")] string Measure15,
        [property: JsonPropertyName("strImageSource")] string ImageSource,
        [property: JsonPropertyName("strImageAttribution")] string ImageAttribution,
        [property: JsonPropertyName("strCreativeCommonsConfirmed")] string CreativeCommonsConfirmed,
        [property: JsonPropertyName("dateModified")] string DateModified);
}


/*
 *       "idDrink": "15521",
      "strDrink": "Swedish Coffee",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Coffee / Tea",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Coffee Mug",
      "strInstructions": "Pour the coffee in an ordinary coffee cup. Add the aquavit. Add sugar by taste. Stir and have a nice evening (morning)",
      "strInstructionsES": null,
      "strInstructionsDE": "Gießen Sie den Kaffee in eine normale Kaffeetasse. Füge den Aquavit hinzu. Nach Belieben Zucker zugeben. Rühren Sie um und genießen Sie einen schönen Abend.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versare il caffè in una normale tazza da cappuccino.\r\nAggiungi l'acquavite.\r\nAggiungere lo zucchero a piacere.\r\nMescola e passa una bella serata/mattina",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ywtrvt1441246783.jpg",
      "strIngredient1": "Coffee",
      "strIngredient2": "Aquavit",
      "strIngredient3": "Sugar",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 cup",
      "strMeasure2": "4 cl ",
      "strMeasure3": "By taste ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-03 03:19:43"
*/